name: GitHub Pages Deploy

on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build WASM and page
        run: npm install && npm run gh-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build